/**
 * OctoBot protocol types
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Account } from '../models/Account';
import { ExchangeConfig } from '../models/ExchangeConfig';

/**
* AccountsState
*/
export class AccountsState {
    'version': string;
    'accounts'?: Array<Account>;
    'exchange_configs'?: Array<ExchangeConfig>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "version",
            "baseName": "version",
            "type": "string",
            "format": ""
        },
        {
            "name": "accounts",
            "baseName": "accounts",
            "type": "Array<Account>",
            "format": ""
        },
        {
            "name": "exchange_configs",
            "baseName": "exchange_configs",
            "type": "Array<ExchangeConfig>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AccountsState.attributeTypeMap;
    }

    public constructor() {
    }
}
