/**
 * OctoBot protocol types
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* EvaluatorConfiguration
*/
export class EvaluatorConfiguration {
    /**
    * Evaluator tentacle class name, e.g. RSIMomentumEvaluator
    */
    'name': string;
    'config': { [key: string]: any; };
    'symbols': Array<string>;
    'include_in_construction_candle'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "config",
            "baseName": "config",
            "type": "{ [key: string]: any; }",
            "format": ""
        },
        {
            "name": "symbols",
            "baseName": "symbols",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "include_in_construction_candle",
            "baseName": "include_in_construction_candle",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return EvaluatorConfiguration.attributeTypeMap;
    }

    public constructor() {
    }
}
